export const PassportRegistryABI = [
  { type: 'constructor', inputs: [{ name: '_admin', type: 'address', internalType: 'address' }], stateMutability: 'nonpayable' },
  { type: 'function', name: 'TIER_NEUTRAL', inputs: [], outputs: [{ name: '', type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'TIER_TRUSTED', inputs: [], outputs: [{ name: '', type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'TIER_TOXIC', inputs: [], outputs: [{ name: '', type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'admin', inputs: [], outputs: [{ name: '', type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'getTier', inputs: [{ name: 'trader', type: 'address' }], outputs: [{ name: '', type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'hasPassport', inputs: [{ name: 'trader', type: 'address' }], outputs: [{ name: '', type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'selfRegister', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'setTier', inputs: [{ name: 'trader', type: 'address' }, { name: 'tier', type: 'uint8' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'batchSetTiers', inputs: [{ name: 'traders', type: 'address[]' }, { name: 'tiers', type: 'uint8[]' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'getTraderTier', inputs: [{ name: 'trader', type: 'address' }], outputs: [{ name: '', type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'hasActivePassport', inputs: [{ name: 'trader', type: 'address' }], outputs: [{ name: '', type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'transferAdmin', inputs: [{ name: 'newAdmin', type: 'address' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'event', name: 'PassportRegistered', inputs: [{ name: 'trader', type: 'address', indexed: true }] },
  { type: 'event', name: 'TierUpdated', inputs: [{ name: 'trader', type: 'address', indexed: true }, { name: 'tier', type: 'uint8', indexed: false }, { name: 'setBy', type: 'address', indexed: true }] },
  { type: 'event', name: 'AdminTransferred', inputs: [{ name: 'prev', type: 'address', indexed: true }, { name: 'next', type: 'address', indexed: true }] },
  { type: 'error', name: 'NotAdmin', inputs: [] },
  { type: 'error', name: 'InvalidTier', inputs: [] },
  { type: 'error', name: 'AlreadyRegistered', inputs: [] },
  { type: 'error', name: 'LengthMismatch', inputs: [] },
] as const
